# -*- coding: utf-8 -*-
"""
Copyright (C) 2026 cibo
This file is part of BluFlow <https://github.com/cubicibo/BluFlow>.

BluFlow is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

BluFlow is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with BluFlow.  If not, see <http://www.gnu.org/licenses/>.
"""

from enum import IntEnum
from typing import BinaryIO, Generator

class MPEGClock(IntEnum):
    PTS = 90000
    STC = 27000000

### The code below this comment is under the MIT License as it was generated by ChatGPT.
def split_annexb(bytestream: bytes) -> list[bytes]:
    """
    This code was written by a LLM, it is thereby under the MIT License.
    """
    nals = []
    i = 0
    while True:
        start = bytestream.find(b'\x00\x00\x01', i)
        if start == -1:
            break
        start += 3
        end = bytestream.find(b'\x00\x00\x01', start)
        if end == -1:
            nals.append(bytestream[start:])
            break
        nals.append(bytestream[start:end])
        i = end
    return nals

def split_annexb_and_yield_nal(fp: BinaryIO, chunk_size: int = 4 << 20) -> Generator[bytes, None, None]:
    bytestream = bytearray()
    while True:
        start = bytestream.find(b'\x00\x00\x01')
        if start == -1:
            if not (new_data := fp.read(chunk_size)):
                break
            bytestream += new_data
            continue
        start += 3
        end = -1
        while end < 0:
            if (end := bytestream.find(b'\x00\x00\x01', start)) < 0:
                if not (new_data := fp.read(chunk_size)):
                    yield bytes(bytestream[start:])
                    return
                else:
                    bytestream += new_data
        yield bytes(bytestream[start:end])
        bytestream = bytestream[end:]
    return